BINANCE_API_SPOT_DOMAIN=www.tokocrypto.com \
BINANCE_API_USD_MARGIN_FUTURES_DOMAIN=www.tokocrypto.com \
BINANCE_API_COIN_MARGIN_FUTURES_DOMAIN=www.tokocrypto.com \
BINANCE_API_KEY=abc123 \
BINANCE_API_SECRET=abc123 \
iex -S mix